### ISSUE TITLE
[11.0] website_logo: logo is ignored

### ISSUE THREAD

**Issue by kwoychesko** [OCA/website#553] opened 2018-12-28 23:18 UTC
The logo set in the Website > Settings does not override the logo set in the Company details. This is true for my site as well as the Runbot site (in the Runbot site you'll see that a human heart serves as the logo, but in Website > Settings there is a picture of a person wearing blue scrubs).

What can I do to help troubleshoot this? I'm happy to work but don't know where to start.

**Comment by pedrobaeza** [comment] 2018-12-28 23:25
Have you refreshed without cache?

**Comment by kwoychesko** [comment] 2018-12-28 23:27
Yes, Chrome and Safari, just to be sure, but it's the Runbot instance, too, so I wouldn't have had that website in my cache anyway.

**Comment by kwoychesko** [comment] 2018-12-28 23:30
To clarify, I mean the "Try Me on Runbot" link for the website_logo module (https://runbot.odoo-community.org/runbot/186/11.0).

**Comment by pedrobaeza** [comment] 2019-01-04 17:14
It seems it's not working indeed. @ernestotejeda can you please check?

**Comment by ernestotejeda** [comment] 2019-01-11 22:52
I think this problem shouldn't be because of website_logo module, maybe it could be a problem of compatibility with website_multi_theme module. I tested website_logo without having installed that module and in Firefox everything worked fine, although in Chromium and Opera it was necessary to delete cache and refresh them. But I also checked that without the website_logo installed when changing the company logo, the backend logo is not updated either, unless the cache is removed and updated (at least that is what happens on my PC).

**Comment by kwoychesko** [comment] 2019-01-18 20:44
It may indeed be a problem with themes, though I don't think it's specific to website_multi_theme:
Vanilla Odoo: 

- Vanilla Odoo: website_logo seems to work
- Vanilla Odoo with a theme by 73Lines (Echelon Theme): website_logo does not work
- OCA Runbot with webiste_multi_theme module: website_logo does not work

The website with the Echelon Theme has never had the website_multi-theme module installed.

I'm not a developer, but I've been learning a bit of python and xml and I'm happy to do whatever I can to help: please tell me if there's somewhere in the code you think I should have a look?

**Comment by pedrobaeza** [comment] 2019-01-18 20:47
The problem is then in the 73Lines theme. Closing as proven that it's not something on the module itself.

**Closed as completed by pedrobaeza** 2019-01-18 20:47 UTC

**Comment by kwoychesko** [comment] 2019-01-18 22:10
Close if you think that's correct, but I think it indicates that website_logo is not working with any theme installed. In my notes above website_logo only works in the no-theme case, which will be pretty rare (I bet 99% of websites have some theme installed). Again I'm happy to explore why website_logo doesn't work when a theme is installed, I just need a little hint where to look. :-)
